converter toWideCString*(s: string):WideCString =
  return newWideCString(s)

# converter toInt*(x: EVENT_GROUPS): int =
#   return int(x)

template enumToInt*(typ: expr): stmt =
  converter toInt*(x: typ): int =
    return int(x)

enumToInt(SCITER_CREATE_WINDOW_FLAGS)
enumToInt(EVENT_GROUPS)
enumToInt(MOUSE_BUTTONS)
enumToInt(KEYBOARD_STATES)
enumToInt(INITIALIZATION_EVENTS)
enumToInt(DRAGGING_TYPE)
enumToInt(MOUSE_EVENTS)
enumToInt(CURSOR_TYPE)
enumToInt(KEY_EVENTS)
enumToInt(FOCUS_EVENTS)
enumToInt(SCROLL_EVENTS)
enumToInt(GESTURE_CMD)
enumToInt(GESTURE_STATE)
enumToInt(GESTURE_TYPE_FLAGS)
enumToInt(DRAW_EVENTS)
enumToInt(BEHAVIOR_EVENTS)
enumToInt(EVENT_REASON)
enumToInt(EDIT_CHANGED_REASON)
enumToInt(BEHAVIOR_METHOD_IDENTIFIERS)
enumToInt(SC_LOAD_DATA_RETURN_CODES)
enumToInt(GFX_LAYER)
enumToInt(SCITER_RT_OPTIONS)
enumToInt(OUTPUT_SUBSYTEMS)
enumToInt(OUTPUT_SEVERITY)
enumToInt(ELEMENT_AREAS)
enumToInt(SCITER_SCROLL_FLAGS)
enumToInt(SET_ELEMENT_HTML)
enumToInt(ELEMENT_STATE_BITS)
enumToInt(CTL_TYPE)
enumToInt(NODE_TYPE)
enumToInt(NODE_INS_TARGET)
enumToInt(GRAPHIN_RESULT)
enumToInt(DRAW_PATH_MODE)
enumToInt(SCITER_LINE_JOIN_TYPE)
enumToInt(SCITER_LINE_CAP_TYPE)
enumToInt(SCITER_TEXT_ALIGNMENT)
enumToInt(SCITER_TEXT_DIRECTION)
enumToInt(REQUEST_RESULT)
enumToInt(REQUEST_RQ_TYPE)
enumToInt(SciterResourceType)
enumToInt(REQUEST_STATE)
enumToInt(VTYPE)
enumToInt(VALUE_UNIT_TYPE)
enumToInt(VALUE_UNIT_TYPE_OBJECT)
enumToInt(VALUE_UNIT_TYPE_STRING)
enumToInt(VALUE_STRING_CVT_TYPE)
enumToInt(VALUE_UNIT_TYPE_DATE)
